#!/usr/bin/env python3
"""
Management utility for the JAM Mission Django project.

This script sets the default settings module and delegates to Django's
`execute_from_command_line` utility.  It mirrors the standard manage.py
generated by `django-admin startproject` but has been customised for
explicitness.
"""
import os
import sys


def main() -> None:
    """Run administrative tasks for the Django project."""
    os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'jammission.settings')
    try:
        from django.core.management import execute_from_command_line  # type: ignore
    except ImportError as exc:
        raise ImportError(
            "Couldn't import Django. Are you sure it's installed and "
            "available on your PYTHONPATH environment variable? Did you "
            "forget to activate a virtual environment?"
        ) from exc
    execute_from_command_line(sys.argv)


if __name__ == '__main__':
    main()